### ISSUE TITLE
Source code is empty

### ISSUE THREAD

**Issue by henry860916** [sociotal/SOCIOTAL#2]
hi ,is there available source code, please?
It seems it is empty.
BTW, is the training or learning process in cloud server?

**Comment by clopez87** [comment]
Hi Henry,
You can find source code and documentation in the different repositories at https://github.com/sociotal (communities manager, context manager, etc. ) but the one called SOCIOTAL which is empty because all the code and info is on the other repos which I'm pointing you. 
Kind regards,
clopez
